# Generated by Django 3.1.7 on 2021-03-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('linkNU', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('numOfChaps', models.IntegerField(default=0)),
                ('novelStatus', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.author')),
                ('category', models.ManyToManyField(to='novels.Category')),
            ],
        ),
    ]
