# Generated by Django 3.1.7 on 2021-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
