# Generated by Django 3.1.7 on 2021-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20210327_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.TextField(default='', max_length=20),
        ),
    ]
