# Generated by Django 3.1.7 on 2021-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(max_length=20),
        ),
    ]
